FROM alpine:3.8
RUN export FROXLOR_VERSION=0.9.39.5 && \
    apk add --update --no-cache \
      curl tar supervisor html2text bash \
      apache2 php7-apache2 php7-cli php7-cgi mysql-client php7-session php-simplexml php7-ctype\
      php7-zip php7-pdo_mysql php7-xml php7-posix php7-mbstring php7-bcmath php7-json php7-curl \
      mysql

